// Example 15: Co-Signing to Satisfy an M-of-N Threshold
//
// A signature threshold is satisfied by DISTINCT keys signing the SAME
// transaction. Signing the same body twice does NOT work: the first signature's
// metadata becomes the transaction's `initiator` and is baked into the header, so
// a second independent signature covers a different transaction hash and neither
// copy reaches the threshold.
//
// The flow is: sign once to build an envelope, co-sign that envelope with each
// additional key, then submit ONCE. Submitting between signatures trips replay
// protection on the signature already on chain.
//
// This example builds a 2-of-3 key book and then creates a data account governed
// by it. That creation needs BOTH authorities to approve: the parent ADI's own
// book (it owns the namespace) and the multi-sig book being installed -- three
// signatures on one envelope. Note the first key signs twice, under two different
// pages: a signature is identified by (key, signer), so those are distinct and
// satisfy two separate authorities.

// Multi-Signature Setup
// Generated by Accumulate Studio
// Network: kermit
//
// NuGet packages:
//   dotnet add package Acme.Net.Sdk
//
// Run with: dotnet run

using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text.Json;
using System.Threading.Tasks;
using Acme.Net.Sdk;
using Acme.Net.Sdk.Protocol;
using Acme.Net.Sdk.Protocol.Generated;
using Acme.Net.Sdk.Signing;
using Acme.Net.Sdk.Transactions;
using Acme.Net.Sdk.Helpers;

class Program
{
    static async Task Main(string[] args)
    {
        var baseUrl = Environment.GetEnvironmentVariable("ACCUMULATE_BASE_URL")
            ?? "https://kermit.accumulatenetwork.io";
        using var client = new Accumulate(baseUrl);
        var helper = new AccumulateHelper(client);
        var txIds = new List<(string Label, string TxId)>();
        try
        {
            // Flow variables (customize these for your use case)
            var adi_name = $"adi-{DateTimeOffset.UtcNow.ToUnixTimeSeconds()}";  // Name for your ADI (e.g., 'my-multisig-adi')


            // =========================================================
            // Generate Keys (Signer 1) (GenerateKeys)
            // =========================================================
            var generateKeysSigner_1Kp = AccKeyPairGenerator.GenerateSignatureKeyPair(SignatureType.ED25519);
            var generateKeysSigner_1Lid = Principal.ComputeUrl(generateKeysSigner_1Kp.GetPublicKey());
            var generateKeysSigner_1Lta = Principal.ComputeUrl(generateKeysSigner_1Kp.GetPublicKey(), new Url("acc://ACME"));
            var generateKeysSigner_1PubKey = generateKeysSigner_1Kp.GetPublicKey();
            var generateKeysSigner_1PubHash = Convert.ToHexString(SHA256.HashData(generateKeysSigner_1PubKey)).ToLowerInvariant();
            Console.WriteLine("Generated keypair:");
            Console.WriteLine($"  Lite Identity: {generateKeysSigner_1Lid}");
            Console.WriteLine($"  Lite Token Account: {generateKeysSigner_1Lta}");
            Console.WriteLine($"  Public Key Hash: {generateKeysSigner_1PubHash}");


            // =========================================================
            // Request Tokens (Faucet)
            // =========================================================
            Console.WriteLine("Requesting tokens from faucet...");
            for (int i = 0; i < 3; i++)
            {
                try
                {
                    var resp = await client.V2.FaucetAsync(generateKeysSigner_1Lta.String());
                    Console.WriteLine($"  Faucet {i + 1}/3: submitted");
                    await Task.Delay(2000);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"  Faucet {i + 1}/3 failed: {ex.Message}");
                }
            }
            Console.WriteLine("Faucet request completed");


            // =========================================================
            // Wait for ACME (WaitForBalance)
            // =========================================================
            Console.WriteLine("Waiting for balance >= 15.00000000...");
            await helper.PollForBalanceAsync(generateKeysSigner_1Lta.String());
            Console.WriteLine("Balance reached");


            // =========================================================
            // Add Credits (Action: AddCredits)
            // =========================================================
            var addCreditsOracle = await helper.GetOracleAsync();
            var addCreditsSigner = new SmartSigner(client.V3, generateKeysSigner_1Kp, generateKeysSigner_1Lid.String());
            var addCreditsResult = await addCreditsSigner.SignSubmitAndWaitAsync(
                generateKeysSigner_1Lta.String(),
                TxBody.AddCredits(
                    generateKeysSigner_1Lid.String(),
                    "1000000000",
                    addCreditsOracle
                )
            );
            if (addCreditsResult.Success)
            {
                Console.WriteLine($"AddCredits SUCCESS - TxID: {addCreditsResult.TxId}");
                if (addCreditsResult.TxId != null) txIds.Add(("AddCredits", addCreditsResult.TxId));
            }
            else
            {
                Console.WriteLine($"AddCredits FAILED: {addCreditsResult.Error}");
            }


            // =========================================================
            // Wait for Credits (WaitForCredits)
            // =========================================================
            Console.WriteLine("Waiting for credits >= 1000...");
            await helper.PollForCreditsAsync(generateKeysSigner_1Lid.String());
            Console.WriteLine("Credits reached");


            // =========================================================
            // Create ADI (Action: CreateIdentity)
            // =========================================================
            var createAdiUrl = $"acc://{adi_name}.acme";
            var createAdiSigner = new SmartSigner(client.V3, generateKeysSigner_1Kp, generateKeysSigner_1Lid.String());
            var createAdiResult = await createAdiSigner.SignSubmitAndWaitAsync(
                generateKeysSigner_1Lta.String(),
                TxBody.CreateIdentity(
                    createAdiUrl,
                    $"{createAdiUrl}/book",
                    generateKeysSigner_1PubHash
                )
            );
            if (createAdiResult.Success)
            {
                Console.WriteLine($"CreateIdentity SUCCESS - TxID: {createAdiResult.TxId}");
                if (createAdiResult.TxId != null) txIds.Add(("CreateIdentity", createAdiResult.TxId));
            }
            else
            {
                Console.WriteLine($"CreateIdentity FAILED: {createAdiResult.Error}");
            }


            // =========================================================
            // Credit Key Page (Action: AddCredits)
            // =========================================================
            var creditKeyPageOracle = await helper.GetOracleAsync();
            var creditKeyPageSigner = new SmartSigner(client.V3, generateKeysSigner_1Kp, generateKeysSigner_1Lid.String());
            var creditKeyPageResult = await creditKeyPageSigner.SignSubmitAndWaitAsync(
                generateKeysSigner_1Lta.String(),
                TxBody.AddCredits(
                    $"{createAdiUrl}/book/1",
                    "1000000000",
                    creditKeyPageOracle
                )
            );
            if (creditKeyPageResult.Success)
            {
                Console.WriteLine($"AddCredits SUCCESS - TxID: {creditKeyPageResult.TxId}");
                if (creditKeyPageResult.TxId != null) txIds.Add(("AddCredits", creditKeyPageResult.TxId));
            }
            else
            {
                Console.WriteLine($"AddCredits FAILED: {creditKeyPageResult.Error}");
            }


            // =========================================================
            // Wait for Key Page Credits (WaitForCredits)
            // =========================================================
            Console.WriteLine("Waiting for credits >= 1000...");
            await helper.PollForCreditsAsync($"{createAdiUrl}/book/1");
            Console.WriteLine("Credits reached");


            // =========================================================
            // Create Multi-Sig Key Book (Action: CreateKeyBook)
            // =========================================================
            var createMultiSigKeyBookSigner = new SmartSigner(client.V3, generateKeysSigner_1Kp, $"{createAdiUrl}/book/1");
            var createMultiSigKeyBookResult = await createMultiSigKeyBookSigner.SignSubmitAndWaitAsync(
                createAdiUrl,
                TxBody.CreateKeyBook(
                    $"{createAdiUrl}/multisig-book",
                    generateKeysSigner_1PubHash
                )
            );
            if (createMultiSigKeyBookResult.Success)
            {
                Console.WriteLine($"CreateKeyBook SUCCESS - TxID: {createMultiSigKeyBookResult.TxId}");
                if (createMultiSigKeyBookResult.TxId != null) txIds.Add(("CreateKeyBook", createMultiSigKeyBookResult.TxId));
            }
            else
            {
                Console.WriteLine($"CreateKeyBook FAILED: {createMultiSigKeyBookResult.Error}");
            }


            // =========================================================
            // Credit Multi-Sig Key Page (Action: AddCredits)
            // =========================================================
            var creditMultiSigKeyPageOracle = await helper.GetOracleAsync();
            var creditMultiSigKeyPageSigner = new SmartSigner(client.V3, generateKeysSigner_1Kp, generateKeysSigner_1Lid.String());
            var creditMultiSigKeyPageResult = await creditMultiSigKeyPageSigner.SignSubmitAndWaitAsync(
                generateKeysSigner_1Lta.String(),
                TxBody.AddCredits(
                    $"{createAdiUrl}/multisig-book/1",
                    "500000000",
                    creditMultiSigKeyPageOracle
                )
            );
            if (creditMultiSigKeyPageResult.Success)
            {
                Console.WriteLine($"AddCredits SUCCESS - TxID: {creditMultiSigKeyPageResult.TxId}");
                if (creditMultiSigKeyPageResult.TxId != null) txIds.Add(("AddCredits", creditMultiSigKeyPageResult.TxId));
            }
            else
            {
                Console.WriteLine($"AddCredits FAILED: {creditMultiSigKeyPageResult.Error}");
            }


            // =========================================================
            // Wait for Multi-Sig Credits (WaitForCredits)
            // =========================================================
            Console.WriteLine("Waiting for credits >= 1000...");
            await helper.PollForCreditsAsync($"{createAdiUrl}/multisig-book/1");
            Console.WriteLine("Credits reached");


            // =========================================================
            // Generate Keys (Signer 2) (GenerateKeys)
            // =========================================================
            var generateKeysSigner_2Kp = AccKeyPairGenerator.GenerateSignatureKeyPair(SignatureType.ED25519);
            var generateKeysSigner_2Lid = Principal.ComputeUrl(generateKeysSigner_2Kp.GetPublicKey());
            var generateKeysSigner_2Lta = Principal.ComputeUrl(generateKeysSigner_2Kp.GetPublicKey(), new Url("acc://ACME"));
            var generateKeysSigner_2PubKey = generateKeysSigner_2Kp.GetPublicKey();
            var generateKeysSigner_2PubHash = Convert.ToHexString(SHA256.HashData(generateKeysSigner_2PubKey)).ToLowerInvariant();
            Console.WriteLine("Generated keypair:");
            Console.WriteLine($"  Lite Identity: {generateKeysSigner_2Lid}");
            Console.WriteLine($"  Lite Token Account: {generateKeysSigner_2Lta}");
            Console.WriteLine($"  Public Key Hash: {generateKeysSigner_2PubHash}");


            // =========================================================
            // Add Signer 2 (Action: UpdateKeyPage)
            // =========================================================
            var addSigner_2Signer = new SmartSigner(client.V3, generateKeysSigner_1Kp, $"{createAdiUrl}/multisig-book/1");
            var addSigner_2Result = await addSigner_2Signer.SignSubmitAndWaitAsync(
                $"{createAdiUrl}/multisig-book/1",
                TxBody.UpdateKeyPage(new List<Dictionary<string, object?>>
                {
                    new Dictionary<string, object?> { ["type"] = "add", ["entry"] = new Dictionary<string, object?> { ["keyHash"] = (object)generateKeysSigner_2PubHash } }
                })
            );
            if (addSigner_2Result.Success)
            {
                Console.WriteLine($"UpdateKeyPage SUCCESS - TxID: {addSigner_2Result.TxId}");
                if (addSigner_2Result.TxId != null) txIds.Add(("UpdateKeyPage", addSigner_2Result.TxId));
            }
            else
            {
                Console.WriteLine($"UpdateKeyPage FAILED: {addSigner_2Result.Error}");
            }


            // =========================================================
            // Generate Keys (Signer 3) (GenerateKeys)
            // =========================================================
            var generateKeysSigner_3Kp = AccKeyPairGenerator.GenerateSignatureKeyPair(SignatureType.ED25519);
            var generateKeysSigner_3Lid = Principal.ComputeUrl(generateKeysSigner_3Kp.GetPublicKey());
            var generateKeysSigner_3Lta = Principal.ComputeUrl(generateKeysSigner_3Kp.GetPublicKey(), new Url("acc://ACME"));
            var generateKeysSigner_3PubKey = generateKeysSigner_3Kp.GetPublicKey();
            var generateKeysSigner_3PubHash = Convert.ToHexString(SHA256.HashData(generateKeysSigner_3PubKey)).ToLowerInvariant();
            Console.WriteLine("Generated keypair:");
            Console.WriteLine($"  Lite Identity: {generateKeysSigner_3Lid}");
            Console.WriteLine($"  Lite Token Account: {generateKeysSigner_3Lta}");
            Console.WriteLine($"  Public Key Hash: {generateKeysSigner_3PubHash}");


            // =========================================================
            // Add Signer 3 (Action: UpdateKeyPage)
            // =========================================================
            var addSigner_3Signer = new SmartSigner(client.V3, generateKeysSigner_1Kp, $"{createAdiUrl}/multisig-book/1");
            var addSigner_3Result = await addSigner_3Signer.SignSubmitAndWaitAsync(
                $"{createAdiUrl}/multisig-book/1",
                TxBody.UpdateKeyPage(new List<Dictionary<string, object?>>
                {
                    new Dictionary<string, object?> { ["type"] = "add", ["entry"] = new Dictionary<string, object?> { ["keyHash"] = (object)generateKeysSigner_3PubHash } }
                })
            );
            if (addSigner_3Result.Success)
            {
                Console.WriteLine($"UpdateKeyPage SUCCESS - TxID: {addSigner_3Result.TxId}");
                if (addSigner_3Result.TxId != null) txIds.Add(("UpdateKeyPage", addSigner_3Result.TxId));
            }
            else
            {
                Console.WriteLine($"UpdateKeyPage FAILED: {addSigner_3Result.Error}");
            }


            // =========================================================
            // Set Threshold (2 of 3) (Action: UpdateKeyPage)
            // =========================================================
            var setThreshold_2Of_3Signer = new SmartSigner(client.V3, generateKeysSigner_1Kp, $"{createAdiUrl}/multisig-book/1");
            var setThreshold_2Of_3Result = await setThreshold_2Of_3Signer.SignSubmitAndWaitAsync(
                $"{createAdiUrl}/multisig-book/1",
                TxBody.UpdateKeyPage(new List<Dictionary<string, object?>>
                {
                    new Dictionary<string, object?> { ["type"] = "setThreshold", ["threshold"] = 2 }
                })
            );
            if (setThreshold_2Of_3Result.Success)
            {
                Console.WriteLine($"UpdateKeyPage SUCCESS - TxID: {setThreshold_2Of_3Result.TxId}");
                if (setThreshold_2Of_3Result.TxId != null) txIds.Add(("UpdateKeyPage", setThreshold_2Of_3Result.TxId));
            }
            else
            {
                Console.WriteLine($"UpdateKeyPage FAILED: {setThreshold_2Of_3Result.Error}");
            }


            // =========================================================
            // Create Data Account Governed by the Multi-Sig Book (Action: CoSign — create_data_account under an M-of-N threshold)
            // =========================================================
            // A threshold needs DISTINCT keys signing the SAME transaction. Signing
            // the body twice does not work: the first signature's metadata becomes
            // the transaction's `initiator` and is baked into the header, so a
            // second independent signature is over a different transaction hash and
            // neither copy reaches the threshold. Co-sign the envelope instead.
            var createDataAccountGovernedByTheMultiSigBookBody = TxBody.CreateDataAccount($"{createAdiUrl}/ms-data", new List<string> { $"{createAdiUrl}/multisig-book" });
            var createDataAccountGovernedByTheMultiSigBookSigner = new SmartSigner(client.V3, generateKeysSigner_1Kp, $"{createAdiUrl}/book/1");
            var createDataAccountGovernedByTheMultiSigBookEnvelope = await createDataAccountGovernedByTheMultiSigBookSigner.SignAsync(
                createAdiUrl,
                createDataAccountGovernedByTheMultiSigBookBody);
            // Co-signer 0: appends a signature to the SAME transaction hash.
            createDataAccountGovernedByTheMultiSigBookEnvelope = await new SmartSigner(client.V3, generateKeysSigner_1Kp, $"{createAdiUrl}/multisig-book/1")
                .SignExistingAsync(createDataAccountGovernedByTheMultiSigBookEnvelope);
            // Co-signer 1: appends a signature to the SAME transaction hash.
            createDataAccountGovernedByTheMultiSigBookEnvelope = await new SmartSigner(client.V3, generateKeysSigner_2Kp, $"{createAdiUrl}/multisig-book/1")
                .SignExistingAsync(createDataAccountGovernedByTheMultiSigBookEnvelope);
            // Submit only once every signature is collected: resubmitting a
            // signature that is already on chain trips replay protection.
            var createDataAccountGovernedByTheMultiSigBookResult = await client.V3.SubmitAsync(createDataAccountGovernedByTheMultiSigBookEnvelope);
            static (bool Rejected, string TxId) createDataAccountGovernedByTheMultiSigBookRead(List<JsonElement> messages)
            {
                var rejected = false;
                var txid = "";
                foreach (var m in messages)
                {
                    if (!m.TryGetProperty("status", out var status)) continue;
                    if (status.TryGetProperty("error", out _)) rejected = true;
                    if (status.TryGetProperty("failed", out var f) && f.ValueKind == JsonValueKind.True) rejected = true;
                    // The transaction's own txID is the first one reported; the
                    // rest belong to the signature messages.
                    if (txid.Length == 0 && status.TryGetProperty("txID", out var t))
                        txid = t.GetString() ?? "";
                }
                return (rejected, txid);
            }
            var (createDataAccountGovernedByTheMultiSigBookRejected, createDataAccountGovernedByTheMultiSigBookTxid) = createDataAccountGovernedByTheMultiSigBookRead(createDataAccountGovernedByTheMultiSigBookResult);
            if (createDataAccountGovernedByTheMultiSigBookRejected)
            {
                Console.WriteLine($"CoSign create_data_account FAILED: {createDataAccountGovernedByTheMultiSigBookResult}");
            }
            else
            {
                // Acceptance is not execution. A transaction that has not reached
                // its threshold is accepted with code "ok" and then sits pending,
                // so the only honest confirmation is the delivered status.
                var createDataAccountGovernedByTheMultiSigBookStatus = "unknown";
                for (var i = 0; i < 30; i++)
                {
                    try
                    {
                        var q = await client.V3.CallAsync("query", new { scope = createDataAccountGovernedByTheMultiSigBookTxid });
                        if (q.TryGetProperty("status", out var s) && s.ValueKind == JsonValueKind.String)
                        {
                            createDataAccountGovernedByTheMultiSigBookStatus = s.GetString() ?? "unknown";
                            if (createDataAccountGovernedByTheMultiSigBookStatus != "pending") break;
                        }
                    }
                    catch
                    {
                        // not indexed yet
                    }
                    await Task.Delay(2000);
                }
                if (createDataAccountGovernedByTheMultiSigBookStatus == "delivered")
                {
                    Console.WriteLine($"CoSign create_data_account DELIVERED with 3 signature(s) - TxID: {createDataAccountGovernedByTheMultiSigBookTxid}");
                }
                else
                {
                    Console.WriteLine($"CoSign create_data_account NOT DELIVERED (status={createDataAccountGovernedByTheMultiSigBookStatus}) - TxID: {createDataAccountGovernedByTheMultiSigBookTxid}");
                }
            }


            Console.WriteLine("\n========== Transaction Summary ==========");
            foreach (var (label, txid) in txIds)
            {
                Console.WriteLine($"  {label}: {txid}");
            }
            Console.WriteLine("Flow completed successfully!");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Flow failed: {ex.Message}");
        }
    }
}
