using System.Security.Cryptography;
using System.Text.Json;
using Acme.Net.Sdk.Codec;
using Acme.Net.Sdk.Protocol;
using Acme.Net.Sdk.Protocol.Generated;
using Acme.Net.Sdk.Protocol.Generated.Protocol;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Acme.Net.Sdk.Tests.Codec;

/// <summary>
/// Golden vectors generated by Go's own marshaler for Accumulate 1.4.6.7 (accumulate @ e1d1db9).
/// Fixture: Vectors/accumulate-1.4.6.7-vectors.json
/// </summary>
public class GoldenVectorTests
{
    private static JsonElement Load() =>
        JsonDocument.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Vectors", "accumulate-1.4.6.7-vectors.json"))).RootElement;

    public static IEnumerable<object[]> Names(string prefix) =>
        Load().EnumerateArray().Select(e => e.GetProperty("name").GetString()!).Where(n => n.StartsWith(prefix)).Select(n => new object[] { n });

    public static IEnumerable<object[]> HeaderNames() => Names("header_");
    public static IEnumerable<object[]> HashLockOptionNames() => Names("hashlockoptions_");
    public static IEnumerable<object[]> TxNames() => Names("tx_");

    private static JsonElement Vec(string name) => Load().EnumerateArray().First(e => e.GetProperty("name").GetString() == name);

    private static object? Conv(JsonElement e) => e.ValueKind switch
    {
        JsonValueKind.Object => e.EnumerateObject().ToDictionary(p => p.Name, p => Conv(p.Value)),
        JsonValueKind.Array => e.EnumerateArray().Select(Conv).ToList(),
        JsonValueKind.String => e.GetString(),
        JsonValueKind.Number => e.GetInt64(),
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        _ => null
    };

    private static Dictionary<string, object?> Dict(JsonElement e) => (Dictionary<string, object?>)Conv(e)!;

    private static string Hex(byte[] b) => Convert.ToHexString(b).ToLowerInvariant();

    // ---- dictionary (wire JSON) codec ----

    [Theory]
    [MemberData(nameof(HeaderNames))]
    public void Header_Dictionary_Matches_Go(string name)
    {
        var v = Vec(name);
        Assert.Equal(v.GetProperty("binaryHex").GetString(), Hex(TransactionCodec.MarshalHeader(Dict(v.GetProperty("json")))));
    }

    [Theory]
    [MemberData(nameof(HashLockOptionNames))]
    public void HashLockOptions_Dictionary_Matches_Go(string name)
    {
        var v = Vec(name);
        Assert.Equal(v.GetProperty("binaryHex").GetString(), Hex(TransactionCodec.MarshalHashLockOptions(Dict(v.GetProperty("json")))));
    }

    [Theory]
    [MemberData(nameof(TxNames))]
    public void Transaction_Dictionary_Hash_Matches_Go(string name)
    {
        var v = Vec(name);
        var j = v.GetProperty("json");
        var hash = TransactionCodec.ComputeTransactionHash(Dict(j.GetProperty("header")), Dict(j.GetProperty("body")));
        Assert.Equal(v.GetProperty("hashHex").GetString(), Hex(hash));
    }

    [Theory]
    [MemberData(nameof(TxNames))]
    public void Transaction_Dictionary_Binary_Matches_Go(string name)
    {
        // Transaction binary = 01 <len header> header 02 <len body> body (both length-prefixed uvarint).
        var v = Vec(name);
        var j = v.GetProperty("json");
        var header = TransactionCodec.MarshalHeader(Dict(j.GetProperty("header")));
        var body = TransactionCodec.MarshalBody(Dict(j.GetProperty("body")));
        using var m = new Acme.Net.Sdk.Support.Marshaller();
        m.WriteBytes(1, header);
        m.WriteBytes(2, body);
        Assert.Equal(v.GetProperty("binaryHex").GetString(), Hex(m.GetBytes()));
    }

    // ---- typed classes ----

    [Theory]
    [MemberData(nameof(HeaderNames))]
    public void Header_Typed_Matches_Go(string name)
    {
        var v = Vec(name);
        var header = JsonConvert.DeserializeObject<TransactionHeader>(v.GetProperty("json").GetRawText())!;
        Assert.Equal(v.GetProperty("binaryHex").GetString(), Hex(header.MarshalBinary()));
    }

    [Theory]
    [InlineData("tx_releaselockedoperation")]
    [InlineData("tx_syntheticlockeddeposit")]
    public void Transaction_Typed_Hash_Matches_Go(string name)
    {
        var v = Vec(name);
        var j = v.GetProperty("json");
        var tx = new Transaction
        {
            Header = JsonConvert.DeserializeObject<TransactionHeader>(j.GetProperty("header").GetRawText()),
            Body = JsonConvert.DeserializeObject<ITransactionBody>(j.GetProperty("body").GetRawText()),
        };
        Assert.Equal(v.GetProperty("hashHex").GetString(), Hex(tx.GetHash()));
    }

    [Fact]
    public void Typed_Header_HashLock_Fluent_Roundtrips_Json()
    {
        var h = new TransactionHeader()
            .WithPrincipal("acc://alice.acme/tokens")
            .WithHashLock(HashLockAlgorithm.SHA256, new byte[32], new DateTimeOffset(2030, 1, 2, 3, 4, 5, TimeSpan.Zero));
        var back = JsonConvert.DeserializeObject<TransactionHeader>(JsonConvert.SerializeObject(h))!;
        Assert.Equal(HashLockAlgorithm.SHA256, back.HashLock!.HashAlgorithm);
        Assert.Equal(h.MarshalBinary(), back.MarshalBinary());
    }

    [Fact]
    public void Header_Without_NewFields_Serializes_Unchanged()
    {
        var h = new TransactionHeader().WithPrincipal("acc://alice.acme/tokens");
        var json = JObject.Parse(JsonConvert.SerializeObject(h));
        Assert.False(json.ContainsKey("hashLock"));
        Assert.False(json.ContainsKey("expire"));
        Assert.False(json.ContainsKey("holdUntil"));
        Assert.False(json.ContainsKey("authorities"));
    }

    // ---- type codes / strictness ----

    [Fact]
    public void TypeCodes_Match_Go()
    {
        Assert.Equal(0x18, TransactionTypeCode.ReleaseLockedOperation);
        Assert.Equal(0x37, TransactionTypeCode.SyntheticLockedDeposit);
        Assert.Equal("releaseLockedOperation", TransactionTypeCode.GetApiName(0x18));
        Assert.Equal(0x37, TransactionTypeCode.FromApiName("syntheticLockedDeposit"));
    }

    [Fact]
    public void Unknown_Body_Type_Still_Rejected()
    {
        Assert.Throws<JsonSerializationException>(() =>
            JsonConvert.DeserializeObject<ITransactionBody>("{\"type\":\"noSuchThing\"}"));
        Assert.ThrowsAny<Exception>(() =>
            TransactionCodec.MarshalBody(new Dictionary<string, object?> { ["type"] = "noSuchThing" }));
    }

    [Fact]
    public void Unknown_HashAlgorithm_Rejected()
    {
        Assert.ThrowsAny<Exception>(() => TransactionCodec.MarshalHashLockOptions(
            new Dictionary<string, object?> { ["hashAlgorithm"] = "md5" }));
        Assert.ThrowsAny<Exception>(() => JsonConvert.DeserializeObject<HashLockOptions>("{\"hashAlgorithm\":\"md5\"}"));
    }

    // ---- header fields 5-8 via the signing API, and the co-sign hand-off ----

    private static readonly byte[] VectorInitiator =
        Enumerable.Range(0, 32).Select(i => (byte)(0xA0 + i % 16)).ToArray();

    private static readonly DateTimeOffset Exp = new(2030, 1, 2, 3, 4, 5, TimeSpan.Zero);
    private static readonly DateTimeOffset ExpireAt = new(2031, 5, 6, 7, 8, 9, TimeSpan.Zero);
    private static readonly string LockHashHex = Convert.ToHexString(Enumerable.Range(1, 32).Select(i => (byte)i).ToArray()).ToLowerInvariant();

    private static Dictionary<string, object?> AllFieldsHeader() =>
        Acme.Net.Sdk.Signing.SmartSigner.BuildHeader(
            "acc://alice.acme/tokens", VectorInitiator, "all", new byte[] { 9 },
            new Acme.Net.Sdk.Signing.HeaderOptions
            {
                Expire = Acme.Net.Sdk.Transactions.TxBody.Expire(ExpireAt),
                HoldUntil = Acme.Net.Sdk.Transactions.TxBody.HoldUntil(5),
                Authorities = new[] { "acc://auth1.acme/book" },
                HashLock = Acme.Net.Sdk.Transactions.TxBody.HashLock("sha256", LockHashHex, Exp),
            });

    [Fact]
    public void BuildHeader_With_HeaderOptions_Matches_Go_AllFields()
    {
        var v = Vec("header_all_fields");
        Assert.Equal(v.GetProperty("binaryHex").GetString(), Hex(TransactionCodec.MarshalHeader(AllFieldsHeader())));
    }

    [Fact]
    public void BuildHeader_With_HashLock_Gives_Go_Transaction_Hash()
    {
        var v = Vec("tx_sendtokens_hashlock");
        var header = Acme.Net.Sdk.Signing.SmartSigner.BuildHeader(
            "acc://alice.acme/tokens", VectorInitiator,
            options: new Acme.Net.Sdk.Signing.HeaderOptions
            { HashLock = Acme.Net.Sdk.Transactions.TxBody.HashLock("sha256", LockHashHex, Exp) });
        var body = Dict(v.GetProperty("json").GetProperty("body"));
        Assert.Equal(v.GetProperty("hashHex").GetString(), Hex(TransactionCodec.ComputeTransactionHash(header, body)));
    }

    [Fact]
    public void BuildHeader_Without_Options_Is_Unchanged()
    {
        var v = Vec("header_plain");
        var h = Acme.Net.Sdk.Signing.SmartSigner.BuildHeader("acc://alice.acme/tokens", VectorInitiator);
        Assert.Equal(new[] { "initiator", "principal" }, h.Keys.OrderBy(k => k).ToArray());
        Assert.Equal(v.GetProperty("binaryHex").GetString(), Hex(TransactionCodec.MarshalHeader(h)));
    }

    // A co-signer receives the initiator's header + body out of band (as JSON) and recomputes the
    // hash it signs. If any header field is lost or mis-typed in transit the hash differs and the
    // signature never aggregates, so the hash must survive each serializer.
    private static readonly Dictionary<string, object?> SendBody = new()
    {
        ["type"] = "sendTokens",
        ["to"] = new List<object?> { new Dictionary<string, object?> { ["url"] = "acc://bob.acme/tokens", ["amount"] = "12345" } },
    };

    [Fact]
    public void CoSigner_Recomputes_Same_Hash_After_SystemTextJson_Roundtrip()
    {
        var header = AllFieldsHeader();
        var expected = TransactionCodec.ComputeTransactionHash(header, SendBody);
        var json = System.Text.Json.JsonSerializer.Serialize(new { header, body = SendBody });
        var doc = System.Text.Json.JsonDocument.Parse(json).RootElement;
        var rtHeader = Dict(doc.GetProperty("header"));
        var rtBody = Dict(doc.GetProperty("body"));
        Assert.Equal(Hex(expected), Hex(TransactionCodec.ComputeTransactionHash(rtHeader, rtBody)));
    }

    [Fact]
    public void CoSigner_Recomputes_Same_Hash_After_Newtonsoft_Roundtrip()
    {
        var header = AllFieldsHeader();
        var expected = TransactionCodec.ComputeTransactionHash(header, SendBody);
        var json = JsonConvert.SerializeObject(new { header, body = SendBody });
        var jo = JObject.Parse(json);
        var rtHeader = jo["header"]!.ToObject<Dictionary<string, object?>>()!;
        var rtBody = jo["body"]!.ToObject<Dictionary<string, object?>>()!;
        Assert.Equal(Hex(expected), Hex(TransactionCodec.ComputeTransactionHash(rtHeader, rtBody)));
    }

    // ---- HashLockOptions validation, v3 models ----

    [Fact]
    public void HashLock_ValidateForSubmit_Mirrors_Node_Rules()
    {
        var now = new DateTimeOffset(2030, 1, 1, 0, 0, 0, TimeSpan.Zero);
        HashLockOptions Lock(HashLockAlgorithm a, int len, TimeSpan? ahead) => new()
        { HashAlgorithm = a, Hash = new byte[len], Expiration = ahead is null ? null : now + ahead };

        Lock(HashLockAlgorithm.SHA256, 32, TimeSpan.FromHours(1)).ValidateForSubmit(now);
        Lock(HashLockAlgorithm.HASH160, 20, TimeSpan.FromDays(30)).ValidateForSubmit(now);
        Assert.Throws<ArgumentException>(() => Lock(HashLockAlgorithm.SHA256, 20, TimeSpan.FromHours(1)).ValidateForSubmit(now));
        Assert.Throws<ArgumentException>(() => Lock(HashLockAlgorithm.HASH160, 32, TimeSpan.FromHours(1)).ValidateForSubmit(now));
        Assert.Throws<ArgumentException>(() => Lock(HashLockAlgorithm.Unknown, 32, TimeSpan.FromHours(1)).ValidateForSubmit(now));
        Assert.Throws<ArgumentException>(() => Lock(HashLockAlgorithm.SHA256, 32, null).ValidateForSubmit(now));
        Assert.Throws<ArgumentException>(() => Lock(HashLockAlgorithm.SHA256, 32, TimeSpan.FromMinutes(9)).ValidateForSubmit(now));
        Assert.Throws<ArgumentException>(() => Lock(HashLockAlgorithm.SHA256, 32, TimeSpan.FromDays(31)).ValidateForSubmit(now));
    }

    [Fact]
    public void Receipt_Parses_New_Fields_And_Tolerates_Old_Responses()
    {
        var r = Acme.Net.Sdk.V3.Receipt.FromJson(System.Text.Json.JsonDocument.Parse(
            "{\"start\":\"ab\",\"end\":\"cd\",\"anchor\":\"ef\",\"entries\":[{\"right\":true,\"hash\":\"01\"}],"
            + "\"localBlock\":12,\"localBlockTime\":\"2030-01-02T03:04:05Z\",\"majorBlock\":3,"
            + "\"forHeight\":9,\"complete\":false,\"partition\":\"bvn0\",\"startsAtMainState\":true}").RootElement);
        Assert.Equal(9UL, r.ForHeight);
        Assert.False(r.Complete);
        Assert.Equal("bvn0", r.Partition);
        Assert.True(r.StartsAtMainState);
        Assert.Single(r.Entries!);

        var old = Acme.Net.Sdk.V3.Receipt.FromJson(System.Text.Json.JsonDocument.Parse(
            "{\"start\":\"ab\",\"localBlock\":12,\"majorBlock\":3}").RootElement);
        Assert.Equal(0UL, old.ForHeight);
        Assert.False(old.StartsAtMainState);
        Assert.Null(old.Partition);
    }

    [Theory]
    [InlineData("{\"seconds\":1,\"nanoseconds\":500000000}", 1UL, 500000000UL)]
    [InlineData("2", 2UL, 0UL)]
    [InlineData("\"1m30s\"", 90UL, 0UL)]
    [InlineData("\"250ms\"", 0UL, 250000000UL)]
    public void NetworkGlobals_BlockInterval_Reads_Every_Wire_Form(string json, ulong sec, ulong ns)
    {
        var g = Acme.Net.Sdk.V3.NetworkGlobals.FromJson(System.Text.Json.JsonDocument.Parse(
            "{\"majorBlockSchedule\":\"0 */12 * * *\",\"anchorEmptyBlocks\":true,\"blockInterval\":" + json + "}").RootElement);
        Assert.Equal(new Acme.Net.Sdk.V3.ProtocolDuration(sec, ns), g.BlockInterval);
        Assert.Equal("0 */12 * * *", g.MajorBlockSchedule);
    }

    [Fact]
    public void NetworkGlobals_Without_BlockInterval_Still_Parses()
    {
        var g = Acme.Net.Sdk.V3.NetworkGlobals.FromJson(System.Text.Json.JsonDocument.Parse(
            "{\"majorBlockSchedule\":\"0 */12 * * *\",\"futureField\":1}").RootElement);
        Assert.Null(g.BlockInterval);
        Assert.True(g.ExtensionData!.ContainsKey("futureField"));
    }
}
